name: "GAC"
version: "1.3.1"
api: ["1.0.0"]
main: cz.creeperface.nukkit.gac.GTAnticheat
author: "CreeperFace"
description: "Basic AntiCheat plugin for Nukkit"
softdepend: ["SynapseAPI"]
depend: ["KotlinLib"]